---
title: "Chase Markdown"
author: "Chase Brewster"
date: "5/22/2019"
output: html_document
---

1. Set Up

```{r setup, include=FALSE}
library(raster)
library(rgdal)
library(rasterVis)
library(maps)
library(rgeos)
library(dplyr)
library(RColorBrewer)
```

2. Read in and Explore Data

```{r}

# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255))

# smaller plotting margins
par(mar=c(2,2,1,1))

# use "getwd()" in console - this tells you the working directory. Added in the threats_data/full_modelnv.tif to read in the specific data we needed from the threats folder

all_threats <- raster("/Users/chasebrewster/Documents/Bren/Spring 2019/ESM 270/Lab 7/CPLab7_Hotspots/Threats_data/full_modelnv.tif")

# plotting the raster really quick

plot(all_threats, col=cols)

# now add a basemap too
# add=T adds the basemap to the original plot, fill=T fills the map (with color gray)

plot(all_threats, ext=extent(-130,-110,24,50),col=cols)
map('world', fill=T, add=T,col='gray')


```

```{r}
# if you type in the raster name into the console, you can see raster information such as dimensions, total pixels, extent, resolution, etc.

# Now, going to zoom in to the santa barbara channel

plot(all_threats,col=cols, ext=extent(-121,-117,32,35), main="Cumulative Threats")
map('world', fill=T, add=T,col='gray')

# also, you can use zoom() function where you draw your own extent, but it doesn't work in markdown (HTML)

# going to zoom in on SF bay

plot(all_threats,col=cols, ext=extent(-123,-121,37,38.5), main="SF Bay")
map('world', fill=T, add=T,col='gray')

```

```{r}
# lets call our raster and get some information

all_threats

# try making a histogram to visualize some data

hist(all_threats,main="Cumulative Threats Frequency")

# cellStats() runs basic stats, super useful - ?cellStats

cellStats(all_threats,mean)
cellStats(all_threats,sd)

```

3. Raster Calculations

```{r}
# need to read in data. already have threats, need species

all_spp <- raster("/Users/chasebrewster/Documents/Bren/Spring 2019/ESM 270/Lab 7/CPLab7_Hotspots/ca_curr_sp_rich.tif")

# look at it 

all_spp

# data appears to be much coarser, and with a different extent

plot(all_spp,col=cols)
map('world', fill=T, add=T,col='gray')

# lets crop and resample to make these rasters the same extents and resolutions

# the threats raster has a larger extent, so we are going to make the threats layer match the species layer

threats_crop <- crop(all_threats, all_spp)

# now they are the same extent, and we need to resample to make them the same resolution
# the threats is at a higher resolution, so we need to make the species resolution match this
# we will use nearest neighbor (method = )
# progress = text will tell us how things are going as it runs

spp_res <- resample(all_spp, threats_crop, method='ngb', progress = 'text')

# now we need to check if they actually line up after our resampling and cropping
# for this we will use the stack() function to make a RasterStack

spp_threat_stack <- stack(threats_crop, spp_res)
plot(spp_threat_stack, col=cols)

# looks good. these wouldn't stack if our crop and resample didn't work (would give an error)
```

```{r}

# we want to find the top 20% of both species richness and threats, and combine them to find hotspots
# we will use reclassify()

# lets start with the species layer

hist(spp_res, main="Species Raster Values")

# there are a lot of zero values and we need to reassign them as they should be no data (NA) and not 0's

# we are overwriting the higher resolution species raster - usually it would be better to make a new object

spp_res <- reclassify(spp_res,rcl=c(-Inf,0,NA))
hist(spp_res,main="Species Raster Values, No Zeroes")
```

```{r}
# so, the zeros are now NA

# now, we just want the top 20% of species
# these cells will have a value of 1, and all other non-NA cells will be 0

# to figure out the quantiles, we can use the quantile() function

spp_cutoff <- quantile(spp_res,0.8) # this will find the exact value at the 80th percentile
spp_maxVal <- cellStats(spp_res,max) # this is the maximumn in the speciues data

# now, we have the cutoff and the maximum
# so we will use the reclassify function to reassign "0" and "1"'s 
# this is a reclassification matrix

rcl_mat <- c(-Inf,spp_cutoff,0,spp_cutoff,spp_maxVal,1) 

# basically, everything up to the cutoff is 0, and the cutoff to the max is 1

# now, reclassify using the matrix

spp_binary <- reclassify(spp_res, rcl=rcl_mat)

# now we have a binary dataset = either, a cell is top 20, or it is not

# let's visualize
# need to change the colors

binary_cols <- c("white","firebrick")

# now, baseplot with R, giving it the color scheme, and adding a basemap below

plot(spp_binary,col=binary_cols,legend=F,main="Top 20% of Species Richness")
map('world', fill=T,add=T,col="gray")
```

```{r}
# Now that we have the top 20% of species, we need to do the same thing to get the threats layer

# visualize the data
# not a lot of zeroes - probably don't need to change them to NA

hist(threats_crop, main="Threats Raster Values")

# now lets find quantiles and resample

threat_cutoff <- quantile(threats_crop,0.8)
threat_maxVal <- cellStats(threats_crop,max)

# now we need the reclassify matrix

rcl_mat_two <- c(-Inf,threat_cutoff,0,threat_cutoff,spp_maxVal,1) 

# now reclassify

threat_binary <- reclassify(threats_crop, rcl=rcl_mat_two)

# now we have a binary dataset = either, a cell is top 20, or it is not

# let's visualize
# need to change the colors

binary_cols <- c("white","firebrick")

# now, baseplot with R, giving it the color scheme, and adding a basemap below

plot(threat_binary,col=binary_cols,legend=F,main="Top 20% of Threats")
map('world', fill=T,add=T,col="gray")
```

```{r}
# now we have our top 20% of threats and species
# so let us combine them for overlap

# overlay function

hotspots <- overlay(spp_binary, threat_binary,fun=function(x,y){x+y})

# so now, cells can have a value of 0,1, or 2
# so lets get new colors

brks_hotspots <- seq(0,3,length.out=4)
hotspot_cols <- c("white", "lightblue", "firebrick")

# okay lets plot them

plot(hotspots,col=hotspot_cols,legend=F,main="Hotspots")
map('world',fill=T,add=T,col='gray80')
```

